In [120]:
import pandas as pd
import numpy as np

# Data Selection

In [121]:
# Load dataset
df = pd.read_csv("japan_international_marriage.csv")

# Preview the dataset
df.head()

,year,both_japanese,husb_jpn_wife_american,husb_jpn_wife_brazilian,husb_jpn_wife_british,husb_jpn_wife_chinese,husb_jpn_wife_filipino,husb_jpn_wife_korean,husb_jpn_wife_other,husb_jpn_wife_peruvian,husb_jpn_wife_thai,wife_jpn_husb_american,wife_jpn_husb_brazilian,wife_jpn_husb_british,wife_jpn_husb_chinese,wife_jpn_husb_filipino,wife_jpn_husb_korean,wife_jpn_husb_other,wife_jpn_husb_peruvian,wife_jpn_husb_thai
0,1965,950696,64,NaN,NaN,121,NaN,843,39,NaN,NaN,1592,NaN,NaN,158,NaN,1128,211,NaN,NaN
1,1970,1023859,75,NaN,NaN,280,NaN,1536,217,NaN,NaN,1571,NaN,NaN,195,NaN,1386,286,NaN,NaN
2,1971,1085639,97,NaN,NaN,325,NaN,1696,232,NaN,NaN,1252,NaN,NaN,194,NaN,1533,261,NaN,NaN
3,1972,1093988,102,NaN,NaN,445,NaN,1785,342,NaN,NaN,1010,NaN,NaN,237,NaN,1707,368,NaN,NaN
4,1973,1065730,122,NaN,NaN,410,NaN,1902,415,NaN,NaN,1024,NaN,NaN,238,NaN,1674,408,NaN,NaN

In [122]:
# Keep a working copy
selected_df = df.copy()

print("Shape of selected dataset:", selected_df.shape)
selected_df.head()

Shape of selected dataset: (56, 20)

,year,both_japanese,husb_jpn_wife_american,husb_jpn_wife_brazilian,husb_jpn_wife_british,husb_jpn_wife_chinese,husb_jpn_wife_filipino,husb_jpn_wife_korean,husb_jpn_wife_other,husb_jpn_wife_peruvian,husb_jpn_wife_thai,wife_jpn_husb_american,wife_jpn_husb_brazilian,wife_jpn_husb_british,wife_jpn_husb_chinese,wife_jpn_husb_filipino,wife_jpn_husb_korean,wife_jpn_husb_other,wife_jpn_husb_peruvian,wife_jpn_husb_thai
0,1965,950696,64,NaN,NaN,121,NaN,843,39,NaN,NaN,1592,NaN,NaN,158,NaN,1128,211,NaN,NaN
1,1970,1023859,75,NaN,NaN,280,NaN,1536,217,NaN,NaN,1571,NaN,NaN,195,NaN,1386,286,NaN,NaN
2,1971,1085639,97,NaN,NaN,325,NaN,1696,232,NaN,NaN,1252,NaN,NaN,194,NaN,1533,261,NaN,NaN
3,1972,1093988,102,NaN,NaN,445,NaN,1785,342,NaN,NaN,1010,NaN,NaN,237,NaN,1707,368,NaN,NaN
4,1973,1065730,122,NaN,NaN,410,NaN,1902,415,NaN,NaN,1024,NaN,NaN,238,NaN,1674,408,NaN,NaN

# Data Inspection

In [123]:
# Basic structure of the dataset
selected_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     56 non-null     int64
 1   both_japanese            56 non-null     int64
 2   husb_jpn_wife_american   56 non-null     int64
 3   husb_jpn_wife_brazilian  33 non-null     float64
 4   husb_jpn_wife_british    33 non-null     float64
 5   husb_jpn_wife_chinese    56 non-null     int64
 6   husb_jpn_wife_filipino   33 non-null     float64
 7   husb_jpn_wife_korean     56 non-null     int64
 8   husb_jpn_wife_other      56 non-null     int64
 9   husb_jpn_wife_peruvian   33 non-null     float64
 10  husb_jpn_wife_thai       33 non-null     float64
 11  wife_jpn_husb_american   56 non-null     int64
 12  wife_jpn_husb_brazilian  33 non-null     float64
 13  wife_jpn_husb_british    33 non-null     float64
 14  wife_jpn_husb_chinese    56 non-null     int64
 15  wife_jpn_husb_filipino   33 non-null     float64
 16  wife_jpn_husb_korean     56 non-null     int64
 17  wife_jpn_husb_other      56 non-null     int64
 18  wife_jpn_husb_peruvian   33 non-null     float64
 19  wife_jpn_husb_thai       33 non-null     float64
dtypes: float64(10), int64(10)
memory usage: 8.9 KB

In [124]:
# Statistical summary
selected_df.describe()

,year,both_japanese,husb_jpn_wife_american,husb_jpn_wife_brazilian,husb_jpn_wife_british,husb_jpn_wife_chinese,husb_jpn_wife_filipino,husb_jpn_wife_korean,husb_jpn_wife_other,husb_jpn_wife_peruvian,husb_jpn_wife_thai,wife_jpn_husb_american,wife_jpn_husb_brazilian,wife_jpn_husb_british,wife_jpn_husb_chinese,wife_jpn_husb_filipino,wife_jpn_husb_korean,wife_jpn_husb_other,wife_jpn_husb_peruvian,wife_jpn_husb_thai
count,56.000000,5.600000e+01,56.000000,33.000000,33.000000,56.000000,33.000000,56.000000,56.000000,33.000000,33.000000,56.000000,33.000000,33.000000,56.000000,33.000000,56.000000,56.000000,33.000000,33.000000
mean,1996.428571,7.265299e+05,202.267857,334.272727,66.242424,4889.571429,5501.848485,3584.142857,2075.017857,114.727273,1334.878788,1128.071429,262.787879,262.727273,638.464286,143.636364,2016.892857,1471.785714,104.787879,39.969697
std,16.440368,1.439229e+05,48.517472,127.056895,16.161355,4005.963327,2541.684531,1913.841405,1610.016877,25.792771,440.181195,305.279119,57.868254,59.777333,303.589973,66.633709,468.034135,867.382284,21.871439,16.470589
min,1965.000000,4.562660e+05,64.000000,209.000000,38.000000,121.000000,1780.000000,843.000000,39.000000,70.000000,637.000000,539.000000,146.000000,168.000000,158.000000,46.000000,1128.000000,211.000000,56.000000,13.000000
25%,1982.750000,6.638145e+05,178.750000,255.000000,53.000000,1614.250000,3371.000000,1993.000000,885.750000,92.000000,976.000000,933.500000,231.000000,222.000000,293.250000,101.000000,1627.750000,515.000000,92.000000,29.000000
50%,1996.500000,7.192785e+05,206.500000,288.000000,62.000000,4229.000000,5771.000000,3153.500000,1966.000000,116.000000,1338.000000,1139.000000,270.000000,240.000000,771.000000,138.000000,1858.000000,1706.500000,106.000000,36.000000
75%,2010.250000,7.668912e+05,237.000000,347.000000,81.000000,7068.500000,7188.000000,5086.750000,2647.250000,138.000000,1688.000000,1376.500000,299.000000,316.000000,857.000000,188.000000,2482.500000,2248.500000,123.000000,54.000000
max,2024.000000,1.093988e+06,286.000000,645.000000,99.000000,13936.000000,12150.000000,8940.000000,8013.000000,166.000000,2137.000000,1592.000000,346.000000,386.000000,1104.000000,269.000000,2842.000000,2783.000000,137.000000,75.000000

In [125]:
# Missing values summary table
missing_summary = selected_df.isnull().sum().reset_index()
missing_summary.columns = ["column", "missing_count"]
missing_summary[missing_summary["missing_count"] > 0]

                     column  missing_count
3   husb_jpn_wife_brazilian             23
4     husb_jpn_wife_british             23
6    husb_jpn_wife_filipino             23
9    husb_jpn_wife_peruvian             23
10       husb_jpn_wife_thai             23
12  wife_jpn_husb_brazilian             23
13    wife_jpn_husb_british             23
15   wife_jpn_husb_filipino             23
18   wife_jpn_husb_peruvian             23
19       wife_jpn_husb_thai             23

In [126]:
# Check duplicate rows
selected_df.duplicated().sum()
# Display duplicate rows if any
selected_df[selected_df.duplicated()]

Empty DataFrame
Columns: [year, both_japanese, husb_jpn_wife_american, husb_jpn_wife_brazilian, husb_jpn_wife_british, husb_jpn_wife_chinese, husb_jpn_wife_filipino, husb_jpn_wife_korean, husb_jpn_wife_other, husb_jpn_wife_peruvian, husb_jpn_wife_thai, wife_jpn_husb_american, wife_jpn_husb_brazilian, wife_jpn_husb_british, wife_jpn_husb_chinese, wife_jpn_husb_filipino, wife_jpn_husb_korean, wife_jpn_husb_other, wife_jpn_husb_peruvian, wife_jpn_husb_thai]
Index: []

# Data Cleaning

In [127]:
clean_df = selected_df.copy()
# Sort by year
clean_df = clean_df.sort_values("year").reset_index(drop=True)

# Remove duplicate rows
clean_df = clean_df.drop_duplicates()

print("Shape after cleaning duplicates:", clean_df.shape)
clean_df.head()

Shape after cleaning duplicates: (56, 20)

,year,both_japanese,husb_jpn_wife_american,husb_jpn_wife_brazilian,husb_jpn_wife_british,husb_jpn_wife_chinese,husb_jpn_wife_filipino,husb_jpn_wife_korean,husb_jpn_wife_other,husb_jpn_wife_peruvian,husb_jpn_wife_thai,wife_jpn_husb_american,wife_jpn_husb_brazilian,wife_jpn_husb_british,wife_jpn_husb_chinese,wife_jpn_husb_filipino,wife_jpn_husb_korean,wife_jpn_husb_other,wife_jpn_husb_peruvian,wife_jpn_husb_thai
0,1965,950696,64,NaN,NaN,121,NaN,843,39,NaN,NaN,1592,NaN,NaN,158,NaN,1128,211,NaN,NaN
1,1970,1023859,75,NaN,NaN,280,NaN,1536,217,NaN,NaN,1571,NaN,NaN,195,NaN,1386,286,NaN,NaN
2,1971,1085639,97,NaN,NaN,325,NaN,1696,232,NaN,NaN,1252,NaN,NaN,194,NaN,1533,261,NaN,NaN
3,1972,1093988,102,NaN,NaN,445,NaN,1785,342,NaN,NaN,1010,NaN,NaN,237,NaN,1707,368,NaN,NaN
4,1973,1065730,122,NaN,NaN,410,NaN,1902,415,NaN,NaN,1024,NaN,NaN,238,NaN,1674,408,NaN,NaN

In [128]:
# Convert all columns except year to numeric
for col in clean_df.columns:
    if col != "year":
        clean_df[col] = pd.to_numeric(clean_df[col], errors="coerce")

clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     56 non-null     int64
 1   both_japanese            56 non-null     int64
 2   husb_jpn_wife_american   56 non-null     int64
 3   husb_jpn_wife_brazilian  33 non-null     float64
 4   husb_jpn_wife_british    33 non-null     float64
 5   husb_jpn_wife_chinese    56 non-null     int64
 6   husb_jpn_wife_filipino   33 non-null     float64
 7   husb_jpn_wife_korean     56 non-null     int64
 8   husb_jpn_wife_other      56 non-null     int64
 9   husb_jpn_wife_peruvian   33 non-null     float64
 10  husb_jpn_wife_thai       33 non-null     float64
 11  wife_jpn_husb_american   56 non-null     int64
 12  wife_jpn_husb_brazilian  33 non-null     float64
 13  wife_jpn_husb_british    33 non-null     float64
 14  wife_jpn_husb_chinese    56 non-null     int64
 15  wife_jpn_husb_filipino   33 non-null     float64
 16  wife_jpn_husb_korean     56 non-null     int64
 17  wife_jpn_husb_other      56 non-null     int64
 18  wife_jpn_husb_peruvian   33 non-null     float64
 19  wife_jpn_husb_thai       33 non-null     float64
dtypes: float64(10), int64(10)
memory usage: 8.9 KB

In [129]:
# Columns where husband is Japanese and wife is foreign
husb_foreign_cols = [col for col in clean_df.columns if col.startswith("husb_jpn_wife_")]

# Columns where wife is Japanese and husband is foreign
wife_foreign_cols = [col for col in clean_df.columns if col.startswith("wife_jpn_husb_")]

print("Husband Japanese + foreign wife columns:")
print(husb_foreign_cols)

print("\nWife Japanese + foreign husband columns:")
print(wife_foreign_cols)

Husband Japanese + foreign wife columns:
['husb_jpn_wife_american', 'husb_jpn_wife_brazilian', 'husb_jpn_wife_british', 'husb_jpn_wife_chinese', 'husb_jpn_wife_filipino', 'husb_jpn_wife_korean', 'husb_jpn_wife_other', 'husb_jpn_wife_peruvian', 'husb_jpn_wife_thai']

Wife Japanese + foreign husband columns:
['wife_jpn_husb_american', 'wife_jpn_husb_brazilian', 'wife_jpn_husb_british', 'wife_jpn_husb_chinese', 'wife_jpn_husb_filipino', 'wife_jpn_husb_korean', 'wife_jpn_husb_other', 'wife_jpn_husb_peruvian', 'wife_jpn_husb_thai']

In [130]:
# Combine all foreign-country categories
clean_df["total_husb_jpn_foreign_wife"] = clean_df[husb_foreign_cols].sum(axis=1, skipna=True)
clean_df["total_wife_jpn_foreign_husband"] = clean_df[wife_foreign_cols].sum(axis=1, skipna=True)

# Drop 1965 to keep a continuous yearly sequence from 1970 onward
clean_df = clean_df[clean_df["year"] != 1965].reset_index(drop=True)

# Total marriages involving a foreign spouse
clean_df["total_foreign_spouse"] = (
    clean_df["total_husb_jpn_foreign_wife"] +
    clean_df["total_wife_jpn_foreign_husband"]
)

# Total marriages
clean_df["total_marriages"] = (
    clean_df["both_japanese"] +
    clean_df["total_foreign_spouse"]
)
clean_df.head()

,year,both_japanese,husb_jpn_wife_american,husb_jpn_wife_brazilian,husb_jpn_wife_british,husb_jpn_wife_chinese,husb_jpn_wife_filipino,husb_jpn_wife_korean,husb_jpn_wife_other,husb_jpn_wife_peruvian,...,wife_jpn_husb_chinese,wife_jpn_husb_filipino,wife_jpn_husb_korean,wife_jpn_husb_other,wife_jpn_husb_peruvian,wife_jpn_husb_thai,total_husb_jpn_foreign_wife,total_wife_jpn_foreign_husband,total_foreign_spouse,total_marriages
0,1970,1023859,75,NaN,NaN,280,NaN,1536,217,NaN,...,195,NaN,1386,286,NaN,NaN,2108.0,3438.0,5546.0,1029405.0
1,1971,1085639,97,NaN,NaN,325,NaN,1696,232,NaN,...,194,NaN,1533,261,NaN,NaN,2350.0,3240.0,5590.0,1091229.0
2,1972,1093988,102,NaN,NaN,445,NaN,1785,342,NaN,...,237,NaN,1707,368,NaN,NaN,2674.0,3322.0,5996.0,1099984.0
3,1973,1065730,122,NaN,NaN,410,NaN,1902,415,NaN,...,238,NaN,1674,408,NaN,NaN,2849.0,3344.0,6193.0,1071923.0
4,1974,994096,142,NaN,NaN,477,NaN,2047,511,NaN,...,229,NaN,1743,420,NaN,NaN,3177.0,3182.0,6359.0,1000455.0

# Data Preparation

In [131]:
jap_copy_df = clean_df[
    [
        "year",
        "both_japanese",
        "total_husb_jpn_foreign_wife",
        "total_wife_jpn_foreign_husband",
        "total_foreign_spouse",
        "total_marriages"
    ]
].copy()

jap_copy_df.head()

,year,both_japanese,total_husb_jpn_foreign_wife,total_wife_jpn_foreign_husband,total_foreign_spouse,total_marriages
0,1970,1023859,2108.0,3438.0,5546.0,1029405.0
1,1971,1085639,2350.0,3240.0,5590.0,1091229.0
2,1972,1093988,2674.0,3322.0,5996.0,1099984.0
3,1973,1065730,2849.0,3344.0,6193.0,1071923.0
4,1974,994096,3177.0,3182.0,6359.0,1000455.0

In [132]:
jap_df = jap_copy_df.melt(
    id_vars="year",
    var_name="type",
    value_name="amount"
)

jap_df.head()

   year           type     amount
0  1970  both_japanese  1023859.0
1  1971  both_japanese  1085639.0
2  1972  both_japanese  1093988.0
3  1973  both_japanese  1065730.0
4  1974  both_japanese   994096.0

In [134]:
jap_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    275 non-null    int64
 1   type    275 non-null    str
 2   amount  275 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 6.6 KB

In [135]:
jap_df.isnull().sum()

year      0
type      0
amount    0
dtype: int64

In [136]:
jap_df["type"].value_counts()

type
both_japanese                     55
total_husb_jpn_foreign_wife       55
total_wife_jpn_foreign_husband    55
total_foreign_spouse              55
total_marriages                   55
Name: count, dtype: int64